### ISSUE TITLE
find 3D Sod tube example and play around with it.

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#112]
Originally reported by: **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**

---

Weekly task of 2015W5

The goal is
- to implement a more comprehensive 3D Sod tube solver. At least to have a analytic solution.
- to understand and implement SOLVCON framework. measurement: a patch of the framework.

There are several tasks:
- initially playing around with the 3D Sod tube example
- implement the analytic solution I
- implement the analytic solution II
- implement the analytic solution III
- implement the analytic solution IIII
- wrapping up this issue.

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/112

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Do you think it's reasonable to target this at v0.1.4?

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

It seems to me that this also depends on the status of 3D Sod tube example.
If it was runnable, I am confident to put it at v0.1.4

I tried to run it and the mesh seemed to have issues:

```
└──╼ ./go 
********************************************************************************
*** Start init (level 0) tube_20 ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start build_domain ... 
*** *** ************************************************************************
*** *** mesh file: None
*** *** ************************************************************************
*** *** *** Start create_block ... 
*** *** *** ********************************************************************
*** *** *** Traceback (most recent call last):
  File "./go", line 127, in <module>
    cse.init()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case_legacy.py", line 441, in init
    loaded = self.load_block()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/kerpak/gasdyn.py", line 196, in load_block
    loaded = super(GasdynCase, self).load_block()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case_legacy.py", line 512, in load_block
    obj = self.io.mesher(self)
  File "./go", line 66, in mesher
    return gn.toblock(bcname_mapper=cse.condition.bcmap)
AttributeError: 'NoneType' object has no attribute 'toblock'
```

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

alright, now question is:
why Cubit(cmds, 3)() return Nonetype??
how to use cubit??

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

gn.g is missing so causing IO error

```
ipdb> gnp
'/tmp/tmpm0mT4S/gn.g'
ipdb> n
IOError: IOError(...ectory',)
> /home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/helper.py(245)__call__()
    244             self.stdout = pobj.stdout.read()
--> 245             gn = Genesis(gnp)
    246             gn.load()

ipdb> n
> /home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/helper.py(248)__call__()
    247             gn.close_file()
--> 248         except:
    249             gn = None

ipdb> n
> /home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/helper.py(249)__call__()
    248         except:
--> 249             gn = None
    250         finally:

ipdb> 
```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Cubit can't be used.  You need to redo the mesh to move on.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

attachment patch 15w17-use-gmsh-for-3d-tube-example-prototype is a proposed solution to enable the example of 3d tube (3D Sod tube) by gmsh instead of Cubit.

It is used for the discussion of the meeting of 150420, not a real patch.

This patch will show:

```
/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/kerpak/gasdyn.pyc in _jacofunc_(self)
    170     @property
    171     def _jacofunc_(self):
--> 172         return self._clib_gasdyn_c.calc_jaco
    173     def calccfl(self, worker=None):
    174         from ctypes import byref

AttributeError: 'NoneType' object has no attribute 'calc_jaco'

```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

The Gmsh file should define boundaries, which will be mapped to SOLVCON boundary-condition treatmemt objects (solvcon.BC) in the arrangement file.  Also, we should port the example to solvcon.parcel.gas form solvcon.kerpak.gasdyn.  Let's discuss it later.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

comment of

#112/find-3d-sod-tube-example-and-play-around#comment-17485191

is caused by lack of lib which should by found by getcdll.

```
solvcon/kerpak/gasdyn.py

class GasdynSolver(CuseSolver):
    """ 
    Gas dynamics solver of the Euler equations.
    """
    def __init__(self, blk, *args, **kw):
        kw['nsca'] = 1 
        super(GasdynSolver, self).__init__(blk, *args, **kw)
    from solvcon.dependency import getcdll
    __clib_gasdyn_c = { 
        2: getcdll('gasdyn2d_c', raise_on_fail=False),
        3: getcdll('gasdyn3d_c', raise_on_fail=False),
    }   
    __clib_gasdyn_cu = { 
        2: getcdll('gasdyn2d_cu', raise_on_fail=False),
        3: getcdll('gasdyn3d_cu', raise_on_fail=False),
    } 
```

calls getcdll

```
solvcon.dependency

def getcdll(libname, location=None, raise_on_fail=True):                                                                                                                                
    """ 
    Load shared objects at the default location.

    @param libname: main basename of library without sc_ prefix.
    @type libname: str
    @keyword location: location of the library.
    @type location: str
    @keyword raise_on_fail: raise the error on failing to load. Default True.
    @type raise_on_fail: bool
    @return: ctypes library.
    @rtype: ctypes.CDLL
    """
    import os
    from .conf import env 
    location = env.libdir if location is None else location
    try:
        lib = loadcdll(location, 'sc_'+libname)


```

and location returned by env.libdir is None as well.

I could remove this issue by replace

```
scons scmods
```

(which is suggested by http://www.solvcon.net/en/latest/)

by

```
scons --cache-disable
```

(which is suggested by contrib/release.sh)

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

now the error message became (as what we have discussed last week, lack of BCs)

```
examples/gasdyn/tube/go

********************************************************************************
*** Start init (level 0) tube_20 ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start build_domain ... 
*** *** ************************************************************************
*** *** mesh file: None
*** *** ************************************************************************
*** *** *** Start create_block ... 
*** *** *** ********************************************************************
*** *** *** ********************************************************************
*** *** *** End create_block . Elapsed time (sec) = 0.495245
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End build_domain . Elapsed time (sec) = 0.495612
*** ****************************************************************************
*** ****************************************************************************
*** End init tube_20 . Elapsed time (sec) = 0.4982
********************************************************************************
********************************************************************************
*** Start run (level 0) tube_20 ... 
*** ****************************************************************************
*** Block information:
***   [Block (3D/centroid): 60 nodes, 338 faces (112 BC), 141 cells]
*** Steps 0/400
*** Traceback (most recent call last):
  File "./go", line 135, in <module>
    cse.run()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case_legacy.py", line 812, in run
    self._run_preloop()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case_legacy.py", line 844, in _run_preloop
    self.solver.solverobj.boundcond()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/kerpak/cuse.py", line 342, in boundcond
    self.call_non_interface_bc('soln')
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/solver_legacy.py", line 548, in call_non_interface_bc
    getattr(bc, name)(*args, **kw)
AttributeError: ('[unspecified#0 "unspecified": 112 faces with 0 values]', 'soln', "'unspecified' object has no attribute 'soln'")

```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

As I commented in #112/find-3d-sod-tube-example-and-play-around#comment-17487040 , we should port the example to solvcon.parcel.gas form solvcon.kerpak.gasdyn.  solvcon.kerpak.gasdyn used the old ctypes approach to bridge C and Python, which should be deprecated.

The BC problem needs to be resolved with Gmsh.  First name the faces, then map them in the arrangement file.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

not a real patch and it is not runable.

material for the discussion on May 11th. 2015

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

```
└──╼ ./go run
********************************************************************************
*** Start init (level 0) tube ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start build_domain ... 
*** *** ************************************************************************
*** *** mesh file: None
*** *** ************************************************************************
*** *** *** Start create_block ... 
*** *** *** ********************************************************************
*** *** *** ********************************************************************
*** *** *** End create_block . Elapsed time (sec) = 90.7176
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End build_domain . Elapsed time (sec) = 90.7178
*** ****************************************************************************
*** ****************************************************************************
*** End init tube . Elapsed time (sec) = 93.9089
********************************************************************************
********************************************************************************
*** Start run ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_provide ... 
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End run_provide . Elapsed time (sec) = 0.157016
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_preloop ... 
*** *** ************************************************************************
*** *** Steps 0/600
*** *** Block information:
*** ***   [Block (3D/centroid): 124591 nodes, 1468874 faces (48236 BC), 722378 cells]
*** *** Traceback (most recent call last):
  File "./go", line 195, in <module>
    sc.go()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/cmdutil.py", line 187, in go
    cmd()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/command.py", line 1091, in __call__
    func(submit=False, **funckw)
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 1083, in simu
    cse.run(level=runlevel)
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 839, in run
    self._run_preloop()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 874, in _run_preloop
    self.solver.solverobj.apply_bc()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/parcel/gas/solver.py", line 149, in apply_bc
    self.call_non_interface_bc('soln')
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/solver.py", line 428, in call_non_interface_bc
    getattr(bc, name)(*args, **kw)
AttributeError: ('[unspecified#0 "unspecified": 48236 faces with 0 values]', 'soln', "'unspecified' object has no attribute 'soln'")

```

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

I think I did not catch how to set up bcmap

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

With your investigation I hope we can develop debugging helpers for setting the bcmap.  Currently we have nothing to teach people how to set it up except obscure document / description (and I don't even remember where it is written).

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

looks like I have set up bcmap for 3d sod tube problem.
I found out the magic numbers of gmsh surface identifications for physical naming by gmsh GUI.
The GUI is easy to use to find those numbers by select "physical groups --> add --> surface" and then move the mouse cursor to where you want to know the information.

Now, I expect I just lack of setting up the physical initialization conditions ( the gas status in left and right zone respectively.) need to figure out where to set them up.

the following is the message dumped by this example/patch

```
$ ./go run
********************************************************************************
*** Start init (level 0) tube ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start build_domain ... 
*** *** ************************************************************************
*** *** mesh file: None
*** *** ************************************************************************
*** *** *** Start create_block ... 
*** *** *** ********************************************************************
*** *** *** Traceback (most recent call last):
  File "./go", line 195, in <module>
    sc.go()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/cmdutil.py", line 187, in go
    cmd()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/command.py", line 1091, in __call__
    func(submit=False, **funckw)
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 1082, in simu
    cse.init(level=runlevel)
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 450, in init
    loaded = self.load_block()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/case.py", line 519, in load_block
    obj = self.io.mesher(self)
  File "./go", line 95, in __call__
    return gmh.toblock(bcname_mapper=cse.condition.bcmap)
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/io/gmsh.py", line 532, in toblock
    blk.build_ghost()
  File "/home/tai271828/work-my-projects/solvcon/solvcon.installed/solvcon/block.py", line 415, in build_ghost
    self.create_msh().build_ghost(self.bndfcs)
  File "mesh.pyx", line 157, in solvcon.mesh.Mesh.build_ghost (solvcon/mesh.c:2880)
IndexError: Out of bounds on buffer access (axis 0)

```

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

hmmm, looks like the error is caused by self.bndfcs = (ndarray)[]

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

bndfcs = boundary face (indices)
it is the sum of all possible boundary faces.

so looks like that I did not really let SOLVCON know which face is a boundary face.

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Right, it's a possibility.  Or you might create bogus boundary faces which
are not set as boundary.  Have you plotted the faces?

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

```
gmsh gmsh.geo -3 -o gmsh.msh
```

I checked gmsh.msh, it is a 2D mesh.
This is kind of weird because I could use

```
gmsh gmsh.geo
```

and gmsh GUI to perform 3D mesh by

```
Modules --> Mesh --> 3D
```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Looks like a Gmsh issue.  I guess you didn't get a correct mesh.  You can
write a simple script to load/convert the .msh file into a
solvcon.block.Block and see if it's 2D or 3D.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

it seems that Physical Volume definition is required to dump 3D mesh.
In this case, use

```
Physical Volume("tube") = {1};
```

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

this 3d sod tube example could perform marching now.
Unfortunately, the parameters or something must be wrong.

For example, at t=0, p is zero all over the tube. 
After 200 steps, p is "infinite" all over the tube.

p should not be zero everywhere in the tube at t=0 because Sod initial conditions are known.

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

You should try to output the solution per each step to see when and where the solution starts to get wrong.  My guess is you weren't setting a correct initial condition.

The attached file `15w27-3d-sod-tube-example-01-could-march` doesn't include `DiaphragmIAnchor` and I don't know how you wrote it.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

there is 

```
cse.defer(gas.DiaphragmIAnchor
......
```

oops, I found I did not export associated modification physics.py including this:

```
class DiaphragmIAnchor(sc.MeshAnchor):
    """
    diaphragm initialization
    """
    def __init__(self, svr, **kw):
        self.rho1 = float(kw.pop('rho1'))
        self.rho2 = float(kw.pop('rho2'))
        self.p1 = float(kw.pop('p1'))
        self.p2 = float(kw.pop('p2'))
        self.gamma = float(kw.pop('gamma'))
        super(DiaphragmIAnchor, self).__init__(svr, **kw)

    def provide(self):
        super(DiaphragmIAnchor, self).provide()
        gamma = self.gamma
        svr = self.svr
        svr.soln[:,0].fill(self.rho1)
        svr.soln[:,1].fill(0.0)
        svr.soln[:,2].fill(0.0)
        if svr.ndim == 3:
            svr.soln[:,3].fill(0.0)
        svr.soln[:,svr.ndim+1].fill(self.p1/(gamma-1))
        # set.
        slct = svr.blk.clcnd[:,2] > 1.0
        svr.soln[slct,0] = self.rho2
        svr.soln[slct,svr.ndim+1] = self.p2
        # update.
        svr.sol[:] = svr.soln[:]

```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

`DiaphragmIAnchor`  is specific to the shock tube problem.  For non-general logic like this, it should be included in the driving script.

The line

```
#!python

svr.soln[slct,svr.ndim+1] = self.p2
```

doesn't look right.  It should be 

```
#!python

svr.soln[slct,svr.ndim+1] = self.p2/(gamma-1)
```

Note the last solution variable is the energy density.  See http://www.solvcon.net/en/latest/gas/euler.html#equation-euler:unknown .

Have you checked your time_increment setting?  How large is the CFL number?  It mustn't be over 1.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

thanks for the p2 issue, fixed.
I copy that line directly from the old example, so it is wrong as well ? : p

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

A driven script to initialize 3D Sod tube conditions by handling ghost cells.
Please note this patch is not completed because
the result is obviously wrong. e.g.

```
CFL = nan/nan - 1.00/0.00 adjusted: 0/0/0
```

![Screenshot from 2015-07-10 23:06:57.png](https://bitbucket.org/repo/R549n/images/2870529180-Screenshot%20from%202015-07-10%2023:06:57.png)
![Screenshot from 2015-07-10 23:23:10.png](https://bitbucket.org/repo/R549n/images/1611928431-Screenshot%20from%202015-07-10%2023:23:10.png)

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Everything in examples/gasdyn/ have been verified.  I don't think it's wrong.

You seem to set too large \Delta t.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

tweak time_increment from 7.e-3 to 7.e-4,
we could get this animation and its associated message:

```
/usr/bin/python2.7 /home/tai271828/work-my-projs/solvcon/15w24-sod3d/examples/gas/tube/go run
********************************************************************************
*** Start init (level 0) tube ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start build_domain ... 
*** *** ************************************************************************
*** *** mesh file: None
*** *** ************************************************************************
*** *** *** Start create_block ... 
*** *** *** ********************************************************************
*** *** *** ********************************************************************
*** *** *** End create_block . Elapsed time (sec) = 0.616164
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End build_domain . Elapsed time (sec) = 0.616312
*** ****************************************************************************
*** ****************************************************************************
*** End init tube . Elapsed time (sec) = 0.623919
********************************************************************************
********************************************************************************
*** Start run ... 
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_provide ... 
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End run_provide . Elapsed time (sec) = 0.0020051
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_preloop ... 
*** *** ************************************************************************
*** *** Steps 0/600
*** *** Block information:
*** ***   [Block (3D/centroid): 1150 nodes, 8924 faces (1848 BC), 4000 cells]
*** *** ************************************************************************
*** *** End run_preloop . Elapsed time (sec) = 0.0555079
*** ****************************************************************************
*** 
*** ****************************************************************************
*** *** Start run_march ... 
*** *** ************************************************************************
*** *** ##################################################
*** *** Step 200/600, 8.4s elapsed, 16.8s left
*** *** CFL = 0.04/0.26 - 0.04/0.26 adjusted: 0/0/0
*** *** Performance of tube:
*** ***   8.38991 seconds in marching solver.
*** ***   0.0419496 seconds/step.
*** ***   10.4874 microseconds/cell.
*** ***   0.0953526 Mcells/seconds.
*** ***   0.476763 Mvariables/seconds.
*** *** ##################################################
*** *** Step 400/600, 19.0s elapsed, 9.5s left
*** *** CFL = 0.05/0.47 - 0.04/0.47 adjusted: 0/0/0
*** *** Performance of tube:
*** ***   19.012 seconds in marching solver.
*** ***   0.0475299 seconds/step.
*** ***   11.8825 microseconds/cell.
*** ***   0.0841576 Mcells/seconds.
*** ***   0.420788 Mvariables/seconds.
*** *** ##################################################
*** *** Step 600/600, 31.1s elapsed, 0.0s left
*** *** CFL = 0.06/0.53 - 0.04/0.53 adjusted: 0/0/0
*** *** ************************************************************************
*** *** End run_march . Elapsed time (sec) = 31.1089
*** ****************************************************************************
*** 
*** ****************************************************************************
*** *** Start run_postloop ... 
*** *** ************************************************************************
*** *** Performance of tube:
*** ***   31.0608 seconds in marching solver.
*** ***   0.051768 seconds/step.
*** ***   12.942 microseconds/cell.
*** ***   0.0772679 Mcells/seconds.
*** ***   0.386339 Mvariables/seconds.
*** *** Averaged maximum CFL = 0.4192.
*** *** ************************************************************************
*** *** End run_postloop . Elapsed time (sec) = 0.000507832
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_exhaust ... 
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End run_exhaust . Elapsed time (sec) = 7.79629e-05
*** ****************************************************************************
*** ****************************************************************************
*** *** Start run_final ... 
*** *** ************************************************************************
*** *** ************************************************************************
*** *** End run_final . Elapsed time (sec) = 6.38962e-05
*** ****************************************************************************
*** ****************************************************************************
*** End run tube . Elapsed time (sec) = 31.1675
********************************************************************************

Process finished with exit code 0
```

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

The CFL number is too small.  You should try to make it to be as close as
possible to (but less than) 1.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref: #112 initialize 3D Sod tube example. Close issue #112 and use issue #127 and #128 to follow up the implementation of 3D Sod tube driven script.

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref: #112 initialize 3D Sod tube example. Close issue #112 and use issue #127 and #128 to follow up the implementation of 3D Sod tube driven script.
