### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#20]
Originally reported by: **David Bilyeu (BitBucket: [david_b](http://bitbucket.org/david_b), GitHub: [david_b](http://github.com/david_b))**

---

Tried to run cuda test case and got this error.
(I compiled this test after commenting out this line 
https://bitbucket.org/yungyuc/solvcon/src/f37462b10ca5/sandbox/cuda/SConscript#cl-37 
)
This was the python error.

david@cuda-togo:cuda$ ./go run
Traceback (most recent call last):
  File "./go", line 29, in <module>
    import cueuler
  File "/home/david/Programs/dunadan/solvcon/sandbox/cuda/cueuler.py", line 23, in <module>
    from solvcon.gendata import AttributeDict
ImportError: No module named solvcon.gend

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/20

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Could you provide the full traceback?  Somehow the message you posted is scrambled.  Also, please use examples/gasdyn/blnt for testing CUDA.  Things in sandboxes is not meant to work every time.

**Comment by yungyuc** [comment]
_Original comment by_ **David Bilyeu (BitBucket: [david_b](http://bitbucket.org/david_b), GitHub: [david_b](http://github.com/david_b))**:

---

error file

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Could you provide the results of export?

**Comment by yungyuc** [comment]
_Original comment by_ **David Bilyeu (BitBucket: [david_b](http://bitbucket.org/david_b), GitHub: [david_b](http://github.com/david_b))**:

---

[solved] removed duplicate solvcese from file path
