### ISSUE TITLE
Support the latest gmsh

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#236]
By using the latest `gmsh` (version `4.8.4-git-72690a6a0`), we will have the following unittest errors:

```
customize UnixCCompiler
............................................................................................................................................................................................................................................................................................................................................E/home/runner/solvcon/solvcon-working/venv-conda/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmpjvf09e83/gmsh.msh'>
  outcome.errors.clear()
E/home/runner/solvcon/solvcon-working/venv-conda/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmpb8ys60nl/gmsh.msh'>
  outcome.errors.clear()
.....................................................SSS
======================================================================
ERROR: testCube (solvcon.tests.test_helper.TestGmsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/solvcon/solvcon/solvcon/tests/test_helper.py", line 82, in testCube
    gmh = Gmsh(cmds)()
  File "/home/runner/solvcon/solvcon/solvcon/helper.py", line 314, in __call__
    gmh.load()
  File "/home/runner/solvcon/solvcon/solvcon/io/gmsh.py", line 264, in load
    self.__dict__.update(loader_map[key]())
KeyError: b'$Entities'

======================================================================
ERROR: testSquare (solvcon.tests.test_helper.TestGmsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/solvcon/solvcon/solvcon/tests/test_helper.py", line 74, in testSquare
    gmh = Gmsh(cmds)()
  File "/home/runner/solvcon/solvcon/solvcon/helper.py", line 314, in __call__
    gmh.load()
  File "/home/runner/solvcon/solvcon/solvcon/io/gmsh.py", line 264, in load
    self.__dict__.update(loader_map[key]())
KeyError: b'$Entities'

----------------------------------------------------------------------
Ran 390 tests in 3.913s

FAILED (SKIP=3, errors=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.298s

OK
```

# Steps to Reproduce
1. Fetch the code https://github.com/tai271828/devenv/tree/dev-solvcon-gmsh-build
2. invoke `./bin/build-application-solvcon-devenv.sh`

You could also see the same steps run by github action and the corresponding result:
https://github.com/tai271828/devenv/runs/2513409246?check_suite_focus=true

**Comment by tai271828** [comment]
If we use gmsh built from source version gmsh_3_0_6, which is the same version as the gmsh provided in https://conda.anaconda.org/yungyuc , we can pass unittest.

Refer to this github action run with gmsh built from source version gmsh_3_0_6:
https://github.com/tai271828/devenv/runs/2530912485?check_suite_focus=true

**Comment by yungyuc** [comment]
@tai271828  Could you confirm whether or not this issue is fixed by #239?

**Comment by tai271828** [comment]
> @tai271828 Could you confirm whether or not this issue is fixed by #239?

Absolutely. Thank you for the heads-up.

**Comment by tai271828** [comment]
I used my laptop (ubuntu-mate 18.04) and `gmsh` build (by `devenv launch solvcon`)looks good

```
real    0m1.123s                                                                                                                                                                                       
user    0m0.649s                                                                                                                                                                                                                    
sys     0m0.452s                                                                                                                                                                                          
done; log file: /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/gmsh-4.8.4-source/build/install.log                                                                                          
Finished building script "/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/scripts/build.d/gmsh". 
```

However my SOLVCON installation breaks
```
Install the project...                                                                         
-- Install configuration: "Release"                                                                                       
-- Up-to-date: /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master/libmarch.cpython-36m-x86_64-linux-gnu.so
make[1]: Leaving directory '/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master/libmarch/build/opt_from_solvcon_py36'
env  /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon/solvcon-working/venv-conda/bin/python3 setup.py build_ext --inplace
running build_ext                                                                                                     
running build_src                                                                                                 
build_src                                                                                                             
building extension "solvcon._march_bridge" sources                                                                       
building extension "solvcon.mesh" sources                                                                               
building extension "solvcon.parcel.fake._algorithm" sources                                                             
building extension "solvcon.parcel.linear._algorithm" sources                                              
building extension "solvcon.parcel.bulk._algorithm" sources                                    
building extension "solvcon.parcel.gas._algorithm" sources                                                             
building extension "solvcon.parcel.vewave._algorithm" sources                                                           
building data_files sources                                                                              
build_src: building npy-pkg config files                                                                 
customize UnixCCompiler                                                                                  
customize UnixCCompiler using my_build_ext                                                                
echo PREFIX=/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon/solvcon-wo$
king/venv-conda                 
PREFIX=/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon/solvcon-working/
venv-conda
echo PYTHON_LIBRARY_DIR=/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon
/solvcon-working/venv-conda/lib/python3.6/site-packages
PYTHON_LIBRARY_DIR=/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon/solv
con-working/venv-conda/lib/python3.6/site-packages
mkdir -p /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/application-solvcon/solvcon-workin
g/venv-conda/lib/python3.6/site-packages ; cp libmarch.*.so /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master /home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/fla
vors/issue236-02/application-solvcon/solvcon-working/venv-conda/lib/python3.6/site-packages
cp: -r not specified; omitting directory '/home/tai271828/work-my-projects/solvcon/issue-236-test/devenv/flavors/issue236-02/src/solvcon-master'
Makefile:128: recipe for target 'install' failed
make: *** [install] Error 1
```

I have not nailed down the issue yet. If the issue is raised by SOLVCON but not devenv, I will file an issue.

**Comment by tai271828** [comment]
In my opinion, we could close the issue because gmsh build is good.

**Comment by yungyuc** [comment]
> In my opinion, we could close the issue because gmsh build is good.

This issue was reported for the unit test failures with an (already built) newer version of gmsh.  I think it was not related with building the third party.

**Comment by tai271828** [comment]
> > In my opinion, we could close the issue because gmsh build is good.
> 
> This issue was reported for the unit test failures with an (already built) newer version of gmsh. I think it was not related with building the third party.

You are right. `devenv` changes a lot recently and it failed to build SOLVCON again. Let me think if I should build SOLVCON with `devenv` or in the other way to verify the unittest fix.

**Comment by tai271828** [comment]
#239 introduced a regression to block me from building SOLVCON and running the unittest. Please refer to this comment for more details regarding how this regression is made https://github.com/solvcon/solvcon/pull/239/files#r718935486 .

**Comment by tai271828** [comment]
With the help of #240 and #239 , the latest 4.8.4 gmsh is supported now!!!

# build log

```
-- Installing: /home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/flavors/issue236-03/usr/share/doc/gmsh/demos/simple_geo/transfinite.geo                                                                                 
-- Installing: /home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/flavors/issue236-03/usr/share/doc/gmsh/demos/struct/Exists_GetForced.geo                                                                                
-- Installing: /home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/flavors/issue236-03/usr/share/doc/gmsh/demos/struct/struct.geo                                                                                          
-- Installing: /home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/flavors/issue236-03/usr/share/man/man1/gmsh.1                                                                                                           
                                                                                                                                                                                                                                   
real    0m0.757s                                                                                                                                                                                                                   
user    0m0.441s                                                                                                                                                                                                                   
sys     0m0.313s                                                                                                                                                                                                                   
done; log file: /home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/flavors/issue236-03/src/gmsh-4.8.4-source/build/install.log                                                                                            
Finished building script "/home/tai271828/work-my-projects/solvcon/sprint-demo/devenv/scripts/build.d/gmsh". 
```


# unittest result

```
...................................................................................................................................................................................................................................
................................................................................................................................................................SSS                                                                
----------------------------------------------------------------------                                                                                                                                                             
Ran 390 tests in 3.830s                                                                                                                                                                                                            
                                                                                                                                                                                                                                   
OK (SKIP=3)                                                                                                                                                                                                                        
.                                                                                                                                                                                                                                  
----------------------------------------------------------------------                                                                                                                                                             
Ran 1 test in 0.321s                                                                                                                                                                                                               
                                                                                                                                                                                                                                   
OK    
```
