### ISSUE TITLE
Solvcon Cubit

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#46]
Originally reported by: **David Bilyeu (BitBucket: [david_b](http://bitbucket.org/david_b), GitHub: [david_b](http://github.com/david_b))**

---

I have found that it can take a long to to generate a mesh file when I use Cubit from inside Solvcon. It does not always happen but when it does it can take over a minute to generate a ~4k mesh.  This the the traceback when I force Solvcon to quit via Ctrl C. 

```
#!python
^CTraceback (most recent call last):
  File "../../scg", line 11, in <module>
    solvcon.go()
  File "/home/david/Programs/dunadan/solvcon/solvcon/cmdutil.py", line 176, in go
    cmd()
  File "/home/david/Programs/dunadan/solvcon/solvcon/command.py", line 735, in __call__
    func(submit=False, **funckw)
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 383, in simu
    case.init(level=runlevel)
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 514, in init
    loaded = self.load_block()
  File "/home/david/Programs/dunadan/feanor/euler.py", line 464, in load_block
    blk = super(EulerCase, self).load_block()
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 589, in load_block
    obj = self.io.mesher(self)
  File "/home/david/Programs/dunadan/feanor/arrangement_euler_ASM_C16.py", line 34, in mesher
    return gn.toblock(bcname_mapper=cse.condition.bcmap)
```

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/46

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

The script in SOLVCON lets CUBIT dump data into /tmp directory.  Could you try to empty the /tmp and try again?
