### ISSUE TITLE
Some example could not run, such as example/elaslin/elcv2d

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#47]
Originally reported by: **Anonymous**

---

when i run the script, the message as follow:

[*******@centostoy elcv2d]$ ./go run

---

**\* Start init (level 0) elcv2d ... 

---

---

**\* **\* Start build_domain ... 

---

**\* **\* mesh file: None

---

**\* **\* **\* Start create_block ... 

---

**\* **\* **\* Traceback (most recent call last):
  File "./go", line 247, in <module>
    solvcon.go()
  File "/usr/lib/python2.6/site-packages/solvcon/cmdutil.py", line 176, in go
    cmd()
  File "/usr/lib/python2.6/site-packages/solvcon/command.py", line 735, in **call**
    func(submit=False, **funckw)
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 383, in simu
    case.init(level=runlevel)
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 514, in init
    loaded = self.load_block()
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 589, in load_block
    obj = self.io.mesher(self)
  File "./go", line 115, in mesher
    return gn.toblock(bcname_mapper=cse.condition.bcmap)
AttributeError: 'NoneType' object has no attribute 'toblock'

Some example can run, such as example/euler/impl. Could you tell me the reason. Thank you.

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/47

**Comment by yungyuc** [comment]
_Original comment by_ **Anonymous**:

---

[lizhiting@centostoy elcv2d]$ ./go run

---

**\* Start init (level 0) elcv2d ... 

---

---

**\* **\* Start build_domain ... 

---

**\* **\* mesh file: None

---

**\* **\* **\* Start create_block ... 

---

**\* **\* **\* Traceback (most recent call last):
  File "./go", line 247, in <module>
    solvcon.go()
  File "/usr/lib/python2.6/site-packages/solvcon/cmdutil.py", line 176, in go
    cmd()
  File "/usr/lib/python2.6/site-packages/solvcon/command.py", line 735, in **call**
    func(submit=False, **funckw)
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 383, in simu
    case.init(level=runlevel)
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 514, in init
    loaded = self.load_block()
  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 589, in load_block
    obj = self.io.mesher(self)
  File "./go", line 115, in mesher
    return gn.toblock(bcname_mapper=cse.condition.bcmap)
AttributeError: 'NoneType' object has no attribute 'toblock'

**Comment by yungyuc** [comment]
_Original comment by_ **Anonymous**:

---

[lizhiting@centostoy elcv2d]$ ./go run

---

**\* Start init (level 0) elcv2d ... 

---

---

**\* **\* Start build_domain ... 

---

**\* **\* mesh file: None

---

**\* **\* **\* Start create_block ... 

---

**\* **\* **\* Traceback (most recent call last):

  File "./go", line 247, in <module>

```
solvcon.go()
```

  File "/usr/lib/python2.6/site-packages/solvcon/cmdutil.py", line 176, in go

```
cmd()
```

  File "/usr/lib/python2.6/site-packages/solvcon/command.py", line 735, in **call**

```
func(submit=False, **funckw)
```

  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 383, in simu

```
case.init(level=runlevel)
```

  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 514, in init

```
loaded = self.load_block()
```

  File "/usr/lib/python2.6/site-packages/solvcon/case.py", line 589, in load_block

```
obj = self.io.mesher(self)
```

  File "./go", line 115, in mesher

```
return gn.toblock(bcname_mapper=cse.condition.bcmap)
```

AttributeError: 'NoneType' object has no attribute 'toblock'

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

It is normal.  You do not have CUBIT (http://cubit.sandia.gov/) installed, so that the example failed to run.  Some examples, including this one, use CUBIT to generate meshes on the fly.  You need to install CUBIT to run the examples.

You need to purchase a license from Sandia National Lab if you want to use CUBIT.  It is a very powerful unstructured mesh generator.  I recommend you to do so.

I am currently working on a GMSH mesh loader for SOLVCON.  GMSH is free software.  After several more releases I will include the new mesh loader and some examples using the mesh format as well.
