### ISSUE TITLE
Legacy case setting steps_dump results into error

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#79]
Originally reported by: **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**

---

Reported by @david_b , setting steps_dump in examples/gasdyn/blnt results into the following traceback:

```
#!

*** *** Traceback (most recent call last):
  File "./go", line 120, in <module>
    solvcon.go()
  File "/home/david/Programs/dunadan/solvcon/solvcon/cmdutil.py", line 175, in go
    cmd()
  File "/home/david/Programs/dunadan/solvcon/solvcon/command.py", line 751, in __call__
    func(submit=False, **funckw)
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 387, in simu
    case.run(level=runlevel)
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 903, in run
    self._run_march()
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 950, in _run_march
    self.dump()
  File "/home/david/Programs/dunadan/solvcon/solvcon/case.py", line 478, in dump
    self.solver.domainobj.unbind()
AttributeError: 'Domain' object has no attribute 'unbind'
```

This error prevents restart to work.

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/79

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Fixes issue #79: Legacy case setting steps_dump results into error

This issue was caused by calling a method
:py:meth:`solvcon.domain.Domain.unbind` (and
:py:meth:`solvcon.domain.Domain.bind` as well), which was a typo.
$root/examples/gasdyn/blnt/go is modified to use steps_dump to detect this
issue.
